language: csharp
os: linux
mono: none
dotnet: 3.0.100
solution: TicTacToeWeb.sln
addons:
  ssh_known_hosts: 157.245.245.39
before_install:
- openssl aes-256-cbc -K $encrypted_502a8cc6fba7_key -iv $encrypted_502a8cc6fba7_iv
  -in deploy_rsa.enc -out /tmp/deploy_rsa -d
- npm install
install:
- "./scripts/build.sh"
jobs:
  include:
  - stage: tests
    script:
    - "./scripts/run_unit_tests.sh"
  - stage: deploy
    if: branch = master 
    before_script:
      - eval "$(ssh-agent -s)"
      - chmod 600 /tmp/deploy_rsa
      - ssh-add /tmp/deploy_rsa
    script: "./scripts/deploy.sh $TTTWConnection"
